### ISSUE TITLE
[Organise] Curreny-converter app location

### ISSUE THREAD

**Issue by tejakummarikuntla** [Freshworks-Developers/krusty-krab-tejakummarikuntla#1]
Hi Team,

May I know any preferred locations for this specific application?
I've found `App Content Guidelines` really helpful for the development.

I'm thinking to use `full_page_app` for now, let me know if I missed any doc reg preferred/suggested locations for the app.
Thank you!

**Comment by velmurugan-balasubramanian** [comment]
Hey @tejakummarikuntla, 

Hope you are well, 
It's totally up to you to choose which location for the app, but for the sake of the agent's convenience to work with the app un ticket view, we'd suggest you use the ticket_sidebar location.

Stay safe :)
